@baseUrl = http://localhost:4000

### Health Check
{{baseUrl}}/health

### Register
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "email":"test2@test.com",
  "username":"test2-user",
  "password":"test1234"
}

### Verify-email
POST {{baseUrl}}/api/auth/verify-email?token=1528aec3-8a2a-42c2-8c8c-becfa6adfeae


### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email":"test2@test.com",
  "password":"test1234"
}

### Refresh
POST {{baseUrl}}/api/auth/refresh

### Forgot-password
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
  "email":"test@test.com"
}

### Reset-password
POST {{baseUrl}}/api/auth/reset-password?token=d3bfb63c-d4e8-476a-850d-68afd1e4e6c3
Content-Type: application/json

{
 "password":"test-password"
}

### Logout
POST {{baseUrl}}/api/auth/logout

### Logout-all
POST {{baseUrl}}/api/auth/logout-all

### Create category
POST {{baseUrl}}/api/categories/
Content-Type: application/json

{
  "name":"programming"
}

### Get all categories
GET {{baseUrl}}/api/categories/ 

### Update category
PATCH {{baseUrl}}/api/categories/416477d1-b58b-4f72-a150-9d121d10c7dd
Content-Type: application/json

{
  "name":"programming languages"
}

### Delete category
DELETE {{baseUrl}}/api/categories/416477d1-b58b-4f72-a150-9d121d10c7dd

### Create tag
POST {{baseUrl}}/api/tags/
Content-Type: application/json

{
  "name":"typescript"
}

### Get all tags
GET {{baseUrl}}/api/tags/ 

### Update tag
PATCH {{baseUrl}}/api/tags/16d64b8b-c305-4aeb-95b0-151015fd6085
Content-Type: application/json

{
  "name":"ecamscript"
}

### Delete tag
DELETE {{baseUrl}}/api/tags/70405163-962d-4c8f-9553-9d173b2cf09e

### Create-post
POST {{baseUrl}}/api/posts/
Content-Type: application/json

{
  "title":"javascript",
  "content":"javascript is a funny language",
  # "status":"PUBLISHED",
  "categories":["programming"],
  "tags":["javascript"],
  "media":["790a1d98-9247-46e3-91d1-c0717969b618"]
} 

### Get all published posts
GET {{baseUrl}}/api/posts/

### Get post by slug
GET {{baseUrl}}/api/posts/slug/javascript-3

### Get post by author-name
GET {{baseUrl}}/api/posts/author/test2-user

### Get my posts
GET {{baseUrl}}/api/posts/me

### Get my bookmarked posts
GET {{baseUrl}}/api/posts/me/bookmarks

### Bookmark post
PUT  {{baseUrl}}/api/posts/f2c40c83-f207-4051-a12e-83a7693f6c3e/bookmark

### Un-Bookmark post
DELETE  {{baseUrl}}/api/posts/f2c40c83-f207-4051-a12e-83a7693f6c3e/bookmark

### Update post
PATCH  {{baseUrl}}/api/posts/c7e32973-1462-4561-ba3d-2efb8bbde3b2
Content-Type: application/json

{
  "content":"brandon eich was the creator of js",
  "status":"PUBLISHED"
}

### Delete post
DELETE   {{baseUrl}}/api/posts/c7e32973-1462-4561-ba3d-2efb8bbde3b2

### Get all posts - ADMIN
GET {{baseUrl}}/api/posts/admin

### Generate presigned-url
POST {{baseUrl}}/api/media/generate-presigned-url
Content-Type: application/json

{
  "filename":"pikachu.png",
  "mimeType":"image/png",
  "usage":"POST"
}

### Upload to s3
PUT presigned-url
Content-Type: image/png

< ./pikachu.png

### Create media
POST {{baseUrl}}/api/media/
Content-Type: application/json

{
  "url": "object-url",
	"mimeType": "image/png",
	"size": 78,
	"type":"IMAGE"
}

### Get all users - ADMIN
GET {{baseUrl}}/api/users/

### Get me
GET {{baseUrl}}/api/users/me

### Update me
PATCH {{baseUrl}}/api/users/me
Content-Type: application/json

{
    "username": "test-two-user",
    "socialLinks": [{
      "platform": "twitter",
      "link": "https://x.com/test-user"
    }],
    "avatar": "https://profile-url.com",
    "bio": "most amazing bio ever written"
}

### Delete me
DELETE {{baseUrl}}/api/users/me

### Update user - ADMIN
PATCH {{baseUrl}}/api/users/0ae02eb2-07aa-413d-a755-9225c4d4463c
Content-Type: application/json

{
   "username": "test-2-user",
    "socialLinks": [{
      "platform": "twitter",
      "link": "https://x.com/test-user"
    }],
    "avatar": "https://profile-url.com",
    "bio": "most amazing bio ever written",
    "role": "ADMIN",
    "status": "SUSPENDED",
    "isVerified": false
}

### Delete user - ADMIN
DELETE {{baseUrl}}/api/users/0ae02eb2-07aa-413d-a755-9225c4d4463c